
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin tmp/slc6_amd64_gcc493/src/CondCore/Utilities/src/CondCoreUtilities/a/CondCoreUtilities_xr.cc_tmp
//--End   tmp/slc6_amd64_gcc493/src/CondCore/Utilities/src/CondCoreUtilities/a/CondCoreUtilities_xr.cc_tmp
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{
names = clnames;
n = sizeof(clnames)/sizeof(char*);
}
