
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin tmp/slc6_amd64_gcc530/src/DataFormats/HLTReco/src/DataFormatsHLTReco/a/DataFormatsHLTReco_xr.cc_tmp
 "LCGReflex/edm::ModuleTime",
 "LCGReflex/std::vector<edm::ModuleTime>",
 "LCGReflex/vector<edm::ModuleTime>",
 "LCGReflex/edm::EventTime",
 "LCGReflex/edm::Wrapper<edm::EventTime>",
 "LCGReflex/HLTPerformanceInfo",
 "LCGReflex/edm::Wrapper<HLTPerformanceInfo>",
 "LCGReflex/HLTPerformanceInfo::Module",
 "LCGReflex/std::vector<HLTPerformanceInfo::Module>",
 "LCGReflex/vector<HLTPerformanceInfo::Module>",
 "LCGReflex/__gnu_cxx::__normal_iterator<const HLTPerformanceInfo::Module*,std::vector<HLTPerformanceInfo::Module> >",
 "LCGReflex/__gnu_cxx::__normal_iterator<const HLTPerformanceInfo::Module*,vector<HLTPerformanceInfo::Module> >",
 "LCGReflex/HLTPerformanceInfo::Path",
 "LCGReflex/std::vector<HLTPerformanceInfo::Path>",
 "LCGReflex/vector<HLTPerformanceInfo::Path>",
 "LCGReflex/__gnu_cxx::__normal_iterator<const HLTPerformanceInfo::Path*,std::vector<HLTPerformanceInfo::Path> >",
 "LCGReflex/__gnu_cxx::__normal_iterator<const HLTPerformanceInfo::Path*,vector<HLTPerformanceInfo::Path> >",
 "LCGReflex/std::vector<edm::Ref<std::vector<reco::RecoEcalCandidate>,reco::RecoEcalCandidate,edm::refhelper::FindUsingAdvance<std::vector<reco::RecoEcalCandidate>,reco::RecoEcalCandidate> > >",
 "LCGReflex/vector<edm::Ref<vector<reco::RecoEcalCandidate>,reco::RecoEcalCandidate,edm::refhelper::FindUsingAdvance<vector<reco::RecoEcalCandidate>,reco::RecoEcalCandidate> > >",
 "LCGReflex/std::vector<edm::Ref<std::vector<reco::Electron>,reco::Electron,edm::refhelper::FindUsingAdvance<std::vector<reco::Electron>,reco::Electron> > >",
 "LCGReflex/vector<edm::Ref<vector<reco::Electron>,reco::Electron,edm::refhelper::FindUsingAdvance<vector<reco::Electron>,reco::Electron> > >",
 "LCGReflex/std::vector<edm::Ref<std::vector<reco::RecoChargedCandidate>,reco::RecoChargedCandidate,edm::refhelper::FindUsingAdvance<std::vector<reco::RecoChargedCandidate>,reco::RecoChargedCandidate> > >",
 "LCGReflex/vector<edm::Ref<vector<reco::RecoChargedCandidate>,reco::RecoChargedCandidate,edm::refhelper::FindUsingAdvance<vector<reco::RecoChargedCandidate>,reco::RecoChargedCandidate> > >",
 "LCGReflex/std::vector<edm::Ref<std::vector<reco::PFTau>,reco::PFTau,edm::refhelper::FindUsingAdvance<std::vector<reco::PFTau>,reco::PFTau> > >",
 "LCGReflex/vector<edm::Ref<vector<reco::PFTau>,reco::PFTau,edm::refhelper::FindUsingAdvance<vector<reco::PFTau>,reco::PFTau> > >",
 "LCGReflex/std::vector<trigger::TriggerObjectType>",
 "LCGReflex/vector<trigger::TriggerObjectType>",
 "LCGReflex/__gnu_cxx::__normal_iterator<const trigger::TriggerObjectType*,std::vector<trigger::TriggerObjectType> >",
 "LCGReflex/__gnu_cxx::__normal_iterator<const trigger::TriggerObjectType*,vector<trigger::TriggerObjectType> >",
 "LCGReflex/trigger::TriggerObject",
 "LCGReflex/std::vector<trigger::TriggerObject>",
 "LCGReflex/vector<trigger::TriggerObject>",
 "LCGReflex/trigger::TriggerRefsCollections",
 "LCGReflex/trigger::TriggerFilterObjectWithRefs",
 "LCGReflex/trigger::TriggerEvent::TriggerFilterObject",
 "LCGReflex/std::vector<trigger::TriggerEvent::TriggerFilterObject>",
 "LCGReflex/vector<trigger::TriggerEvent::TriggerFilterObject>",
 "LCGReflex/trigger::TriggerEvent",
 "LCGReflex/trigger::TriggerEventWithRefs::TriggerFilterObject",
 "LCGReflex/std::vector<trigger::TriggerEventWithRefs::TriggerFilterObject>",
 "LCGReflex/vector<trigger::TriggerEventWithRefs::TriggerFilterObject>",
 "LCGReflex/trigger::TriggerEventWithRefs",
 "LCGReflex/edm::Wrapper<std::vector<trigger::TriggerObject> >",
 "LCGReflex/edm::Wrapper<vector<trigger::TriggerObject> >",
 "LCGReflex/edm::Wrapper<trigger::TriggerFilterObjectWithRefs>",
 "LCGReflex/edm::Wrapper<trigger::TriggerEvent>",
 "LCGReflex/edm::Wrapper<trigger::TriggerEventWithRefs>",
 "LCGReflex/std::map<std::string,std::vector<unsigned int> >",
 "LCGReflex/map<string,vector<unsigned int> >",
 "LCGReflex/trigger::HLTPrescaleTable",
 "LCGReflex/edm::Wrapper<trigger::HLTPrescaleTable>",
 "LCGReflex/trigger::TriggerObjectType",
//--End   tmp/slc6_amd64_gcc530/src/DataFormats/HLTReco/src/DataFormatsHLTReco/a/DataFormatsHLTReco_xr.cc_tmp
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{
names = clnames;
n = sizeof(clnames)/sizeof(char*);
}
