
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin tmp/slc6_amd64_gcc530/src/DataFormats/L1TCalorimeter/src/DataFormatsL1TCalorimeter/a/DataFormatsL1TCalorimeter_xr.cc_tmp
 "LCGReflex/l1t::CaloEmCand",
 "LCGReflex/BXVector<l1t::CaloEmCand>",
 "LCGReflex/edm::Wrapper<BXVector<l1t::CaloEmCand> >",
 "LCGReflex/l1t::CaloRegion",
 "LCGReflex/BXVector<l1t::CaloRegion>",
 "LCGReflex/edm::Wrapper<BXVector<l1t::CaloRegion> >",
 "LCGReflex/l1t::CaloTower",
 "LCGReflex/BXVector<l1t::CaloTower>",
 "LCGReflex/edm::Wrapper<BXVector<l1t::CaloTower> >",
 "LCGReflex/l1t::CaloCluster",
 "LCGReflex/BXVector<l1t::CaloCluster>",
 "LCGReflex/edm::Wrapper<BXVector<l1t::CaloCluster> >",
//--End   tmp/slc6_amd64_gcc530/src/DataFormats/L1TCalorimeter/src/DataFormatsL1TCalorimeter/a/DataFormatsL1TCalorimeter_xr.cc_tmp
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{
names = clnames;
n = sizeof(clnames)/sizeof(char*);
}
