
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin tmp/slc6_amd64_gcc530/src/DataFormats/L1TGlobal/src/DataFormatsL1TGlobal/a/DataFormatsL1TGlobal_xr.cc_tmp
 "LCGReflex/GlobalAlgBlk",
 "LCGReflex/BXVector<GlobalAlgBlk>",
 "LCGReflex/edm::Wrapper<BXVector<GlobalAlgBlk> >",
 "LCGReflex/GlobalExtBlk",
 "LCGReflex/BXVector<GlobalExtBlk>",
 "LCGReflex/edm::Wrapper<BXVector<GlobalExtBlk> >",
//--End   tmp/slc6_amd64_gcc530/src/DataFormats/L1TGlobal/src/DataFormatsL1TGlobal/a/DataFormatsL1TGlobal_xr.cc_tmp
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{
names = clnames;
n = sizeof(clnames)/sizeof(char*);
}
