
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin tmp/slc6_amd64_gcc493/src/L1Trigger/L1TNtuples/src/L1TriggerL1TNtuples/a/L1TriggerL1TNtuples_xr.cc_tmp
 "LCGReflex/L1Analysis::L1AnalysisEventDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisCSCTFDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisDTTFDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisGCTDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisGMTDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisGTDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisRCTDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisCaloTPDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisGeneratorDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisSimulationDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisL1ExtraDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisRecoMuonDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisRecoRpcHitDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisRecoJetDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisRecoMetFilterDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisRecoMetDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisRecoClusterDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisRecoVertexDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisRecoTrackDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisL1MenuDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisL1UpgradeDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisL1CaloTowerDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisL1CaloClusterDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisRecoTauDataFormat",
 "LCGReflex/L1Analysis::L1AnalysisRecoMuon2DataFormat",
 "LCGReflex/L1Analysis::L1AnalysisRecoElectronDataFormat",
//--End   tmp/slc6_amd64_gcc493/src/L1Trigger/L1TNtuples/src/L1TriggerL1TNtuples/a/L1TriggerL1TNtuples_xr.cc_tmp
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{
names = clnames;
n = sizeof(clnames)/sizeof(char*);
}
