
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin tmp/slc6_amd64_gcc530/src/DataFormats/L1TMuon/src/DataFormatsL1TMuon/a/DataFormatsL1TMuon_xr.cc_tmp
 "LCGReflex/l1t::RegionalMuonCand",
 "LCGReflex/BXVector<l1t::RegionalMuonCand>",
 "LCGReflex/edm::Wrapper<BXVector<l1t::RegionalMuonCand> >",
 "LCGReflex/l1t::MuonCaloSum",
 "LCGReflex/BXVector<l1t::MuonCaloSum>",
 "LCGReflex/edm::Wrapper<BXVector<l1t::MuonCaloSum> >",
 "LCGReflex/l1t::EMTFOutput",
 "LCGReflex/std::vector<l1t::EMTFOutput>",
 "LCGReflex/vector<l1t::EMTFOutput>",
 "LCGReflex/edm::Wrapper<std::vector<l1t::EMTFOutput> >",
 "LCGReflex/edm::Wrapper<vector<l1t::EMTFOutput> >",
 "LCGReflex/l1t::emtf::AMC13Header",
 "LCGReflex/l1t::emtf::MTF7Header",
 "LCGReflex/l1t::emtf::EventHeader",
 "LCGReflex/l1t::emtf::Counters",
 "LCGReflex/l1t::emtf::ME",
 "LCGReflex/std::vector<l1t::emtf::ME>",
 "LCGReflex/vector<l1t::emtf::ME>",
 "LCGReflex/l1t::emtf::RPC",
 "LCGReflex/std::vector<l1t::emtf::RPC>",
 "LCGReflex/vector<l1t::emtf::RPC>",
 "LCGReflex/l1t::emtf::SP",
 "LCGReflex/std::vector<l1t::emtf::SP>",
 "LCGReflex/vector<l1t::emtf::SP>",
 "LCGReflex/l1t::emtf::EventTrailer",
 "LCGReflex/l1t::emtf::MTF7Trailer",
 "LCGReflex/l1t::emtf::AMC13Trailer",
//--End   tmp/slc6_amd64_gcc530/src/DataFormats/L1TMuon/src/DataFormatsL1TMuon/a/DataFormatsL1TMuon_xr.cc_tmp
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{
names = clnames;
n = sizeof(clnames)/sizeof(char*);
}
